# Polymarket On-Chain Viability Sample

This notebook mirrors the established `Polymarket_data` project at a deliberately small scale. The upstream project builds a full historical dataset by fetching Polymarket `OrderFilled` logs from Polygon, decoding the event payloads, joining CLOB token IDs to Gamma market metadata, and producing analysis-ready `trades`, `quant`, and `users` tables.

Here we run the same style of pipeline for a tiny recent block window only. The goal is not completeness; it is to prove that the data path is viable on this machine before committing to a larger backfill.

## What is copied from `Polymarket_data`

The established project's shape is:

1. Fetch market metadata from Polymarket Gamma API.
2. Fetch `OrderFilled` logs from Polygon RPC for Polymarket exchange contracts.
3. Decode event topics and ABI-encoded data into an `orderfilled` table.
4. Extract trades by identifying the non-USDC CTF asset, normalizing raw amounts by `1e6`, and joining token IDs to market metadata.
5. Produce `quant` by flipping token2 prices into a unified token1/Yes perspective.
6. Produce `users` by splitting each trade into maker and taker rows.

This notebook keeps those same concepts, but it fetches only tokens observed in the tiny on-chain sample instead of crawling the full Gamma market catalog.

## Current contract note

The bundled `Polymarket_data` repo targets the older v1 CTF exchange addresses. Polymarket's current documentation lists v2 exchange addresses, and v2 has a redesigned `OrderFilled` event with `side`, `tokenId`, `makerAmountFilled`, `takerAmountFilled`, `fee`, `builder`, and `metadata` fields.

The helper module supports both v1 and v2 decoders. The default recent-block viability sample uses v2 because current blocks are expected to contain v2 events, while v1 may be inactive after the 2026 CLOB v2 migration.

In [1]:
from pathlib import Path
import json
import sys

import pandas as pd
from IPython.display import display

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from prediction_market.polymarket_onchain import run_and_save_onchain_sample

OUTPUT_DIR = PROJECT_ROOT / "data" / "onchain_sample"

# A tiny timeframe: Polygon blocks are roughly a few seconds apart.
# Increase LOOKBACK_BLOCKS after this notebook proves the path works.
LOOKBACK_BLOCKS = 3
BATCH_SIZE = 1
MAX_EVENTS = 250

pd.set_option("display.max_columns", 80)
pd.set_option("display.max_colwidth", 140)
pd.set_option("display.width", 180)

## Run the small on-chain sample

This cell queries Polygon RPC for recent `OrderFilled` logs, decodes up to `MAX_EVENTS`, fetches Gamma metadata only for observed token IDs, writes raw and processed artifacts, and returns the in-memory tables.

If the public RPC endpoint is slow or empty for a block, re-run the cell or set `POLYGON_RPC_URL` to your own Polygon RPC endpoint before starting Jupyter.

In [2]:
result = run_and_save_onchain_sample(
    OUTPUT_DIR,
    lookback_blocks=LOOKBACK_BLOCKS,
    batch_size=BATCH_SIZE,
    max_events=MAX_EVENTS,
)

sample = result["sample"]
paths = result["paths"]

summary = sample["summary"]
display(pd.DataFrame([summary]).T.rename(columns={0: "value"}))

                                                   value
retrieved_at                        2026-06-06T22:09:19Z
rpc_url           https://polygon-bor-rpc.publicnode.com
start_block                                     88052514
end_block                                       88052516
lookback_blocks                                        3
batch_size                                             1
max_events                                           250
truncated                                           True
failed_ranges                                         []
decoded_events                                       250
unique_token_ids                                      59
matched_markets                                       33
trades_rows                                          250
quant_rows                                           143
users_rows                                           286

In [3]:
print("Raw files:")
for name, path in paths["raw"].items():
    print(f"  {name}: {path.relative_to(PROJECT_ROOT)}")

print("\nProcessed Parquet files:")
for name, path in paths["processed"].items():
    print(f"  {name}: {path.relative_to(PROJECT_ROOT)}")

print("\nCSV previews:")
for name, path in paths["latest_result"].items():
    print(f"  {name}: {path.relative_to(PROJECT_ROOT)}")

Raw files:
  summary: data/onchain_sample/raw/summary.json
  orderfilled_logs: data/onchain_sample/raw/orderfilled_logs.json
  gamma_markets: data/onchain_sample/raw/gamma_markets.json

Processed Parquet files:
  events: data/onchain_sample/processed/orderfilled.parquet
  token_mapping: data/onchain_sample/processed/market_token_mapping.parquet
  trades: data/onchain_sample/processed/trades.parquet
  quant: data/onchain_sample/processed/quant.parquet
  users: data/onchain_sample/processed/users.parquet

CSV previews:
  events: data/onchain_sample/latest_result/orderfilled.csv
  token_mapping: data/onchain_sample/latest_result/market_token_mapping.csv
  trades: data/onchain_sample/latest_result/trades.csv
  quant: data/onchain_sample/latest_result/quant.csv
  users: data/onchain_sample/latest_result/users.csv

## Raw logs and decoded `orderfilled`

Raw logs preserve the original Polygon payload. The decoded `orderfilled` table mirrors the upstream project's first processed layer: block number, transaction hash, log index, contract, maker, taker, token IDs, filled amounts, and event-specific fee fields.

In [4]:
raw_logs = sample["raw_logs"]
print(f"Raw logs captured: {len(raw_logs)}")
if raw_logs:
    print(json.dumps(raw_logs[0], indent=2, sort_keys=True)[:4000])

events = sample["events"]
display(events.drop(columns=["raw_log"]).head(20))

Raw logs captured: 250
{
  "address": "0xe111180000d2663c0091e4f400237545b87b996b",
  "blockHash": "0x552e60d688b24f2ead483b41bbfda9f4d11a3f85bb348abb8e39f7918fa2f39e",
  "blockNumber": "0x53f9322",
  "blockTimestamp": "0x6a249a8c",
  "data": "0x0000000000000000000000000000000000000000000000000000000000000000ec46d0169140e97af27f57b6471fecfc8a692eaa8c93b47691f164d5fdb3e5260000000000000000000000000000000000000000000000000000000002c779800000000000000000000000000000000000000000000000000000000002e51e90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "logIndex": "0x13f",
  "removed": false,
  "topics": [
    "0xd543adfd945773f1a62f74f0ee55a5e3b9b1a28262980ba90b1a89f2ea84d8ee",
    "0x1f2b120d52d2bbfbd2ff8ef5886c9134719b33008407f696d97e577bbb33d8d2",
    "0x000000000000000000000000caad1b3a62d286214f94ace993a1e80e44aa255c",
    "0x000000000000000000000000fd16bdd047ecdb6c006a9f159c14c8bbb7462c91"
  ],
  "transactionHash": "0x8d8f5f7d15e8d55860604830df7edf1af816bdaa21ea95036f9c0e7d16933218",
  "transactionIndex": "0x25"
}

,transaction_hash,block_number,log_index,timestamp,datetime,contract,contract_generation,event_name,order_hash,maker,taker,maker_asset_id,taker_asset_id,side,side_label,token_id,maker_amount_filled,taker_amount_filled,maker_fee,taker_fee,protocol_fee,fee,builder,metadata
0,0x8d8f5f7d15e8d55860604830df7edf1af816bdaa21ea95036f9c0e7d16933218,88052514,319,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x1f2b120d52d2bbfbd2ff8ef5886c9134719b33008407f696d97e577bbb33d8d2,0xcaad1b3a62d286214f94ace993a1e80e44aa255c,0xfd16bdd047ecdb6c006a9f159c14c8bbb7462c91,0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,BUY,106870947731841299226931869706163862462989258483960759258537831115103115928870,46627200,48570000,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
1,0x8d8f5f7d15e8d55860604830df7edf1af816bdaa21ea95036f9c0e7d16933218,88052514,322,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x1b4d4f7be3306b43a54630de46eb5b01dc1c55d3676c887fb955624e658e3823,0xfd16bdd047ecdb6c006a9f159c14c8bbb7462c91,0xe111180000d2663c0091e4f400237545b87b996b,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,1,SELL,106870947731841299226931869706163862462989258483960759258537831115103115928870,48570000,46627200,0,0,0,130550,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
2,0x75e9c920a369d446b4a8d350d5b1c25b1dc63c39304fa9bd607bf81571f1a766,88052514,328,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0xdc5cb48aa552995edb952bf2b0434df01e20808a,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,1,SELL,106870947731841299226931869706163862462989258483960759258537831115103115928870,2000000,1940000,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
3,0x75e9c920a369d446b4a8d350d5b1c25b1dc63c39304fa9bd607bf81571f1a766,88052514,330,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x72685190475bb1cde27664f511be30d53b2480c98603b0bc96565de5351a6853,0xdc5cb48aa552995edb952bf2b0434df01e20808a,0xe111180000d2663c0091e4f400237545b87b996b,0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,BUY,106870947731841299226931869706163862462989258483960759258537831115103115928870,1940000,2000000,0,0,0,4070,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
4,0xd8b15166989fe01858f90a81798ae183ee70a25c620197b18397c5281b30005a,88052514,336,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x16bc7faccdb6dedd07d47333a6f06fef635dd23a,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,1,SELL,106870947731841299226931869706163862462989258483960759258537831115103115928870,22500000,21825000,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
5,0xd8b15166989fe01858f90a81798ae183ee70a25c620197b18397c5281b30005a,88052514,338,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x3e2309f4eaa78cd7789f991f936ff6b8de3465529c3fc8777d13c71b02e79aab,0x16bc7faccdb6dedd07d47333a6f06fef635dd23a,0xe111180000d2663c0091e4f400237545b87b996b,0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,BUY,106870947731841299226931869706163862462989258483960759258537831115103115928870,21825000,22500000,0,0,0,45830,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
6,0xe1db1908adb3bd175eb4cdc15549f31b680fc6b9f366e672ed97e8a2c0460786,88052514,344,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x04e8f45e8ed3662347b2b8686c3ed9dfad1b6d247b70795d05bcc0ca5580d51c,0x98da26e8fa92fc7973af6f95baf5efc4e2493b56,0x674887d1ac838099a48b629dff53f25b7b87ee08,0,114452155101132071341035941016658939783020858202809214057500414093543091573082,0,BUY,114452155101132071341035941016658939783020858202809214057500414093543091573082,430000,4300000,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
7,0xe1db1908adb3bd175eb4cdc15549f31b680fc6b9f366e672ed97e8a2c0460786,88052514,347,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0xd0785400d1a717277872e0f3a70fc60b717c25afc19709bf1442f50d6951ea38,0x674887d1ac838099a48b629dff53f25b7b87ee08,0xe111180000d2663c0091e4f400237545b87b996b,114452155101132071341035941016658939783020858202809214057500414093543091573082,0,1,SELL,114452155101132071341035941016658939783020858202809214057500414093543091573082,4300000,430000,0,0,0,27090,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
8,0x5ac0f5ea6c01482e4aacd7f2259ca54727ee7b98ee9fd048e0694fbdba64024a,88052514,353,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0xf898c9739a8b6ae576f4efcadf7241a64b49fffc,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,1,SELL,106870947731841299226931869706163862462989258483960759258537831115103115928870,60000000,58200000,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
9,0x5ac0f5ea6c01482e4aacd7f2259ca54727ee7b98ee9fd048e0694fbdba64024a,88052514,355,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x4c7f5aa2d0d5316a135d39e7176f304352af219a47dd60a56bab6c146aef034e,0xf898c9739a8b6ae576f4efcadf7241a64b49fffc,0xe111180000d2663c0091e4f400237545b87b996b,0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,BUY,106870947731841299226931869706163862462989258483960759258537831115103115928870,58200000,60000000,0,0,0,122220,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
10,0x726666827b35fdaf692982fc61c085fe3fee2bee5cf01a973a0b64425109c375,88052514,372,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x6e24f356067594bc5320e635150d882cfca6055c88d3f0f3ac245180d82befd9,0x098c8fe3e2e915715e8b4c013ad43b433ca21c67,0x2b9c090d15f1c94d44a81c4880de6f3a8b078927,0,23072918760322003953834133091938577549710981434898330780243901892346723175335,0,BUY,23072918760322003953834133091938577549710981434898330780243901892346723175335,7260000,22000000,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
11,0x726666827b35fdaf692982fc61c085fe3fee2bee5cf01a973a0b64425109c375,88052514,376,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x03bb34d56033706ed42784e64f4451f0120c1237d8812912b0727a0e48d88225,0x2b9c090d15f1c94d44a81c4880de6f3a8b078927,0xe111180000d2663c0091e4f400237545b87b996b,0,93875522406881330816662731472890482041551054506856307552246473115634975932107,0,BUY,93875522406881330816662731472890482041551054506856307552246473115634975932107,14740000,22000000,0,0,0,145920,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
12,0xabaf3ab1a18f096b20caffa8428371cd7b0cad32f95cec8f54c15042f6830307,88052514,381,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x0448f9df3a55876f234245e59e288b740cd486d9,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,1,SELL,106870947731841299226931869706163862462989258483960759258537831115103115928870,5154638,4999998,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
13,0xabaf3ab1a18f096b20caffa8428371cd7b0cad32f95cec8f54c15042f6830307,88052514,383,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x3fbc2db611d9e7372d2c279e793c73b72504b9fd3b9b7e15295f6b5690ea613a,0x0448f9df3a55876f234245e59e288b740cd486d9,0xe111180000d2663c0091e4f400237545b87b996b,0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0,BUY,106870947731841299226931869706163862462989258483960759258537831115103115928870,4999998,5154638,0,0,0,10500,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
14,0xc7a7e4a0d7569003b6bf089706dd76404f4afa02db9e567fe85b67e4ce790136,88052514,389,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0xc9961bf673e3db49834a0e7890e8dbd349af63a9ef3cf3e7fd453757ae743e9f,0x2ed94d1a460379292d2e3b46f2cf7d94b033f271,0xed89b210faa8d83a0484291b8c06b5d717dddf85,0,7705923800682500862272350897127800049020938240555080668886595577732534640441,0,BUY,7705923800682500862272350897127800049020938240555080668886595577732534640441,200000,4000000,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
15,0xc7a7e4a0d7569003b6bf089706dd76404f4afa02db9e567fe85b67e4ce790136,88052514,392,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0xc8fab0ab448391dcc5068e43ee917f60f8fcc212820590014b93351faed0186c,0xed89b210faa8d83a0484291b8c06b5d717dddf85,0xe111180000d2663c0091e4f400237545b87b996b,7705923800682500862272350897127800049020938240555080668886595577732534640441,0,1,SELL,7705923800682500862272350897127800049020938240555080668886595577732534640441,4000000,200000,0,0,0,13300,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
16,0xadd7ac69089bbd5faf4042044bb7511034d907090ff20450874a9cbf14ebdead,88052514,455,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0xa7fe2b76a68fa24a12e9c12b8db97f35c3f4eb2e650e1ad649ef817e0270c689,0x93511d72d294f1478739bc38f578bf0306fd9e4d,0xd83df2a0ed02e608a5d4bc8d4bf4b322f4fb4678,0,79503879558000863984423353516801517784351760207093629712308932082454207172191,0,BUY,79503879558000863984423353516801517784351760207093629712308932082454207172191,248000000,250000000,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
17,0xadd7ac69089bbd5faf4042044bb7511034d907090ff20450874a9cbf14ebdead,88052514,459,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0x8c8649fc767dc2cd11a4773ba5954d5511018d4c505606bcb3eeb66f5bc71792,0xd83df2a0ed02e608a5d4bc8d4bf4b322f4fb4678,0xe111180000d2663c0091e4f400237545b87b996b,0,25759554244493354767227852844420516405380702219740675120053478060935865126097,0,BUY,25759554244493354767227852844420516405380702219740675120053478060935865126097,2000000,250000000,0,0,0,79360,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
18,0x61a8014d845c72de25723c80c148d72ddcd5ad1f10396fc968cef137fc39c335,88052514,487,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0xc35bab3257e18c6312a4657b9608cb5fad5d0b687fcda73924cb9b0e2e9e70bc,0xbf17c1643131948cc5aecb890e915b124e7540be,0x9919a655c2694462950d9ca5a0307202740a0a5d,0,41686662825191984631745612539353248083087678877167731994748991779176910374012,0,BUY,41686662825191984631745612539353248083087678877167731994748991779176910374012,181978,2021977,0,0,0,0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
19,0x61a8014d845c72de25723c80c148d72ddcd5ad1f10396fc968cef137fc39c335,88052514,491,1780783756,2026-06-06T22:09:16Z,CTF_EXCHANGE_V2,v2,OrderFilled,0xc16c37f0cd427182318529901010eefeb0cfd792a950dd498db1902799c8745e,0x9919a655c2694462950d9ca5a0307202740a0a5d,0xe111180000d2663c0091e4f400237545b87b996b,0,59879328752383442614140229014234327720098339084993477538503772314944394059012,0,BUY,59879328752383442614140229014234327720098339084993477538503772314944394059012,1839999,2021977,0,0,0,11590,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000

## Gamma token mapping

The full upstream project fetches and maintains a complete `markets.parquet`. This viability sample does a smaller join: it extracts token IDs from observed logs, asks Gamma for only those token IDs, and builds `token_id -> market` mappings for the sample.

In [5]:
token_mapping = sample["token_mapping"]
display(token_mapping.drop(columns=["raw_payload"]).head(30))

unmatched_tokens = sorted(set(events["token_id"].dropna().astype(str)) - set(token_mapping["token_id"].dropna().astype(str))) if not events.empty else []
print(f"Observed unique token IDs: {events['token_id'].nunique() if not events.empty else 0}")
print(f"Mapped token IDs: {token_mapping['token_id'].nunique() if not token_mapping.empty else 0}")
print(f"Unmatched observed token IDs: {len(unmatched_tokens)}")
if unmatched_tokens:
    print(unmatched_tokens[:10])

,token_id,market_id,condition_id,side,answer,question,event_id,event_slug,event_title,slug,active,closed,end_date
0,19394319214140646671941741664381705243202267892747350778544673112122629257973,2438947,0xd527d369e0f5d7b31f78a22e0ccb40fd0475f1b5c638b4f32a6cfe46ad88f690,token1,Up,"XRP Up or Down - June 6, 6PM ET",559980,xrp-up-or-down-june-6-2026-6pm-et,"XRP Up or Down - June 6, 6PM ET",xrp-up-or-down-june-6-2026-6pm-et,True,False,2026-06-06T23:00:00Z
1,100511062230478552212135043736276339188083946001738935434341228273920332914741,2438947,0xd527d369e0f5d7b31f78a22e0ccb40fd0475f1b5c638b4f32a6cfe46ad88f690,token2,Down,"XRP Up or Down - June 6, 6PM ET",559980,xrp-up-or-down-june-6-2026-6pm-et,"XRP Up or Down - June 6, 6PM ET",xrp-up-or-down-june-6-2026-6pm-et,True,False,2026-06-06T23:00:00Z
2,31164334329147454586598351177849035944989772929947123529371470108985530543953,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,token1,Up,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",btc-updown-5m-1780783500,True,False,2026-06-06T22:10:00Z
3,106870947731841299226931869706163862462989258483960759258537831115103115928870,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,token2,Down,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",btc-updown-5m-1780783500,True,False,2026-06-06T22:10:00Z
4,11709025336479019570959926169364154508096878905561934832983242232548084043273,2448222,0xdcc76b249412818c5336caf58aadfaf1ec1f8216e772d43936eec0a54e8cb96e,token1,Up,"XRP Up or Down - June 6, 6:05PM-6:10PM ET",563573,xrp-updown-5m-1780783500,"XRP Up or Down - June 6, 6:05PM-6:10PM ET",xrp-updown-5m-1780783500,True,False,2026-06-06T22:10:00Z
5,107588686919681972319972959473167522533909429810342062111677120152968428287974,2448222,0xdcc76b249412818c5336caf58aadfaf1ec1f8216e772d43936eec0a54e8cb96e,token2,Down,"XRP Up or Down - June 6, 6:05PM-6:10PM ET",563573,xrp-updown-5m-1780783500,"XRP Up or Down - June 6, 6:05PM-6:10PM ET",xrp-updown-5m-1780783500,True,False,2026-06-06T22:10:00Z
6,77604671816165649880193320279872939595250175691723251969237094641211185350049,2456148,0xaee270f117ab24d9a865def58474583df25dbe2870af4dfa734968397fc45322,token1,Yes,Will the highest temperature in Paris be 23°C on June 8?,566654,highest-temperature-in-paris-on-june-8-2026,Highest temperature in Paris on June 8?,highest-temperature-in-paris-on-june-8-2026-23c,True,False,2026-06-08T12:00:00Z
7,108184724425608771735828556185909553446466947170307951362782981055498577335128,2456148,0xaee270f117ab24d9a865def58474583df25dbe2870af4dfa734968397fc45322,token2,No,Will the highest temperature in Paris be 23°C on June 8?,566654,highest-temperature-in-paris-on-june-8-2026,Highest temperature in Paris on June 8?,highest-temperature-in-paris-on-june-8-2026-23c,True,False,2026-06-08T12:00:00Z
8,76339066435834419633431563584009610571270345858031834833226699514847391136686,2305292,0x6e8e96058b8cd0047156ba7c2db0839926b8be52ad9903948ee14f5c2166442a,token1,Over,Cabo Verde vs. Bermuda: O/U 4.5,503126,fif-cvi-ber-2026-06-06-more-markets,Cabo Verde vs. Bermuda - More Markets,fif-cvi-ber-2026-06-06-total-4pt5,True,False,2026-06-06T20:00:00Z
9,108731524654123509997510843344654240937427302880300958042509229562248362996002,2305292,0x6e8e96058b8cd0047156ba7c2db0839926b8be52ad9903948ee14f5c2166442a,token2,Under,Cabo Verde vs. Bermuda: O/U 4.5,503126,fif-cvi-ber-2026-06-06-more-markets,Cabo Verde vs. Bermuda - More Markets,fif-cvi-ber-2026-06-06-total-4pt5,True,False,2026-06-06T20:00:00Z
10,21023492097258610370659147779530374628303756654061322374421043807882438237493,2456146,0xca2178be56479883bd92db67291f5bcf51023e452295464fb87d2e41facaf425,token1,Yes,Will the highest temperature in Paris be 21°C on June 8?,566654,highest-temperature-in-paris-on-june-8-2026,Highest temperature in Paris on June 8?,highest-temperature-in-paris-on-june-8-2026-21c,True,False,2026-06-08T12:00:00Z
11,108750644329835880001678704329627595348414862057829465240599937824692258149926,2456146,0xca2178be56479883bd92db67291f5bcf51023e452295464fb87d2e41facaf425,token2,No,Will the highest temperature in Paris be 21°C on June 8?,566654,highest-temperature-in-paris-on-june-8-2026,Highest temperature in Paris on June 8?,highest-temperature-in-paris-on-june-8-2026-21c,True,False,2026-06-08T12:00:00Z
12,110669970070373132655248461102832810138230744419178258353211648391397556926754,2444063,0x48f888418459478da09d2f2fa2b1d609b6d72498a13bd683ee844039f35f2675,token1,Abyssal,Counter-Strike: Abyssal vs Ding Cuts (BO3) - Dfrag Open Series #5 Group A,562243,cs2-abyssa-dingcu-2026-06-08,Counter-Strike: Abyssal vs Ding Cuts (BO3) - Dfrag Open Series #5 Group A,cs2-abyssa-dingcu-2026-06-08,True,False,2026-06-08T14:30:00Z
13,113934530937960674330125963172822173881422942206768881164020353756667463515255,2444063,0x48f888418459478da09d2f2fa2b1d609b6d72498a13bd683ee844039f35f2675,token2,Ding Cuts,Counter-Strike: Abyssal vs Ding Cuts (BO3) - Dfrag Open Series #5 Group A,562243,cs2-abyssa-dingcu-2026-06-08,Counter-Strike: Abyssal vs Ding Cuts (BO3) - Dfrag Open Series #5 Group A,cs2-abyssa-dingcu-2026-06-08,True,False,2026-06-08T14:30:00Z
14,7705923800682500862272350897127800049020938240555080668886595577732534640441,2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,token1,Up,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",563560,btc-updown-15m-1780783200,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",btc-updown-15m-1780783200,True,False,2026-06-06T22:15:00Z
15,111805008051229228091804322263095327957845604833734001217212700892269746239782,2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,token2,Down,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",563560,btc-updown-15m-1780783200,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",btc-updown-15m-1780783200,True,False,2026-06-06T22:15:00Z
16,61594851917845046863756783196540033519655644339689420079793185248292111735512,2298908,0x57930dc3e9ed94d824a74cf44487ef2d4fc722854f957ec2ae02e316b5574f3e,token1,Yes,Will SpaceX's valuation hit (HIGH) $3.5T by June 30?,500558,will-spacexs-valuation-hit-by-june-30,Will SpaceX's valuation hit __ by June 30?,will-spacexs-valuation-hit-high-3pt5t-by-june-30,True,False,2026-07-01T12:00:00Z
17,111955313050107562363663664749376439050061635382095754277177971556591609059639,2298908,0x57930dc3e9ed94d824a74cf44487ef2d4fc722854f957ec2ae02e316b5574f3e,token2,No,Will SpaceX's valuation hit (HIGH) $3.5T by June 30?,500558,will-spacexs-valuation-hit-by-june-30,Will SpaceX's valuation hit __ by June 30?,will-spacexs-valuation-hit-high-3pt5t-by-june-30,True,False,2026-07-01T12:00:00Z
18,5409446529282596799645125527168810255623158667214943834411576822383765801301,2445288,0x73eb05e0558aa43e46efeb72357b4f5afdaf4f9281f154e41b67df7a88726f7f,token1,Up,Ethereum Up or Down on June 7?,562575,ethereum-up-or-down-on-june-7-2026,Ethereum Up or Down on June 7?,ethereum-up-or-down-on-june-7-2026,True,False,2026-06-07T16:00:00Z
19,112593023655163136267072327384292074031326518380624796579048302172603186039662,2445288,0x73eb05e0558aa43e46efeb72357b4f5afdaf4f9281f154e41b67df7a88726f7f,token2,Down,Ethereum Up or Down on June 7?,562575,ethereum-up-or-down-on-june-7-2026,Ethereum Up or Down on June 7?,ethereum-up-or-down-on-june-7-2026,True,False,2026-06-07T16:00:00Z
20,114452155101132071341035941016658939783020858202809214057500414093543091573082,2448220,0x1eb6352998233b4a191a8d30ac54e6fe73f07992d4b47d2085b2e0511eedfa40,token1,Up,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",563572,eth-updown-5m-1780783500,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",eth-updown-5m-1780783500,True,False,2026-06-06T22:10:00Z
21,75920722555341482689410813891710208839033832595713473141774780039416335070196,2448220,0x1eb6352998233b4a191a8d30ac54e6fe73f07992d4b47d2085b2e0511eedfa40,token2,Down,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",563572,eth-updown-5m-1780783500,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",eth-updown-5m-1780783500,True,False,2026-06-06T22:10:00Z
22,16047817349313224689230983807626671479723222697866510327546130422926794427178,2407743,0x23493c82fe910057f58cee266768fd6cc3ed04a20c4f7827f6995f5c6c1f172e,token1,FlyQuest,LoL: FlyQuest vs Team Liquid (BO5) - LCS Playoffs,546960,lol-fly-tl2-2026-06-06,LoL: FlyQuest vs Team Liquid (BO5) - LCS Playoffs,lol-fly-tl2-2026-06-06,True,False,2026-06-07T02:00:00Z
23,9188783727936264077380906306618836297681731617053495001158987534737898683153,2407743,0x23493c82fe910057f58cee266768fd6cc3ed04a20c4f7827f6995f5c6c1f172e,token2,Team Liquid,LoL: FlyQuest vs Team Liquid (BO5) - LCS Playoffs,546960,lol-fly-tl2-2026-06-06,LoL: FlyQuest vs Team Liquid (BO5) - LCS Playoffs,lol-fly-tl2-2026-06-06,True,False,2026-06-07T02:00:00Z
24,16101991792807572993968793193076653506578869365903106938925362150189822514827,898666,0x115401967f653200b41852811453cb5aac5052f339af0a63920fb84e6485f316,token1,Yes,Will Haas be the 2026 F1 Constructors' Champion?,100394,f1-constructors-champion,F1 Constructors' Champion,will-haas-be-the-2026-f1-constructors-champion,True,False,2026-12-06T00:00:00Z
25,26004623248415836323463371716552453805887711931731610066624253547449183275938,898666,0x115401967f653200b41852811453cb5aac5052f339af0a63920fb84e6485f316,token2,No,Will Haas be the 2026 F1 Constructors' Champion?,100394,f1-constructors-champion,F1 Constructors' Champion,will-haas-be-the-2026-f1-constructors-champion,True,False,2026-12-06T00:00:00Z
26,56869956455595673840037636611743588892652800745302213251065466294787440676855,2448225,0x44ceac272939803432b3380c8c866758f104fd20ce5e25fbf497bc208db696f8,token1,Up,"Bitcoin Up or Down - June 6, 6:10PM-6:15PM ET",563574,btc-updown-5m-1780783800,"Bitcoin Up or Down - June 6, 6:10PM-6:15PM ET",btc-updown-5m-1780783800,True,False,2026-06-06T22:15:00Z
27,17598259080202703116393337198876972111331011202434683720798985042384494039710,2448225,0x44ceac272939803432b3380c8c866758f104fd20ce5e25fbf497bc208db696f8,token2,Down,"Bitcoin Up or Down - June 6, 6:10PM-6:15PM ET",563574,btc-updown-5m-1780783800,"Bitcoin Up or Down - June 6, 6:10PM-6:15PM ET",btc-updown-5m-1780783800,True,False,2026-06-06T22:15:00Z
28,23072918760322003953834133091938577549710981434898330780243901892346723175335,2453470,0x1cd6790426a19dff12d911967be5719a09af77ae1a3f68cdc848f5106ea3c78c,token1,Over,Games Total: O/U 4.5,565556,lol-kt-dk-2026-06-07,LoL: KT Rolster vs Dplus KIA (BO5) - LCK Road to MSI,lol-kt-dk-2026-06-07-total-games-4pt5,True,False,2026-06-07T14:00:00Z
29,93875522406881330816662731472890482041551054506856307552246473115634975932107,2453470,0x1cd6790426a19dff12d911967be5719a09af77ae1a3f68cdc848f5106ea3c78c,token2,Under,Games Total: O/U 4.5,565556,lol-kt-dk-2026-06-07,LoL: KT Rolster vs Dplus KIA (BO5) - LCK Road to MSI,lol-kt-dk-2026-06-07-total-games-4pt5,True,False,2026-06-07T14:00:00Z

Observed unique token IDs: 59
Mapped token IDs: 66
Unmatched observed token IDs: 0

## Trades

The `trades` table follows the established project's extraction logic. The non-USDC asset is the outcome token. Raw amounts are divided by `1e6`, and price is `USDC amount / token amount`.

For v2 events, `side=BUY` means the maker is buying `tokenId` with collateral; `side=SELL` means the maker is selling `tokenId` for collateral. The notebook preserves `builder` and `metadata` from v2 events as extra attribution fields.

In [6]:
trades = sample["trades"]
display(trades.head(30))

if not trades.empty:
    display(
        trades.groupby(["contract_generation", "contract", "maker_direction", "nonusdc_side"], dropna=False)
        .agg(rows=("transaction_hash", "count"), usd_amount=("usd_amount", "sum"), avg_price=("price", "mean"))
        .reset_index()
        .sort_values("rows", ascending=False)
    )

,timestamp,datetime,block_number,transaction_hash,log_index,contract,contract_generation,event_id,event_slug,event_title,market_id,condition_id,question,nonusdc_side,answer,maker,taker,maker_asset,taker_asset,maker_direction,taker_direction,price,usd_amount,token_amount,fee_amount,asset_id,order_hash,builder,metadata
0,1780783756,2026-06-06T22:09:16Z,88052514,0x8d8f5f7d15e8d55860604830df7edf1af816bdaa21ea95036f9c0e7d16933218,319,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xcaad1b3a62d286214f94ace993a1e80e44aa255c,0xfd16bdd047ecdb6c006a9f159c14c8bbb7462c91,USDC,token2,BUY,SELL,0.960,46.627200,48.570000,0.00000,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x1f2b120d52d2bbfbd2ff8ef5886c9134719b33008407f696d97e577bbb33d8d2,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
1,1780783756,2026-06-06T22:09:16Z,88052514,0x8d8f5f7d15e8d55860604830df7edf1af816bdaa21ea95036f9c0e7d16933218,322,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xfd16bdd047ecdb6c006a9f159c14c8bbb7462c91,0xe111180000d2663c0091e4f400237545b87b996b,token2,USDC,SELL,BUY,0.960,46.627200,48.570000,0.13055,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x1b4d4f7be3306b43a54630de46eb5b01dc1c55d3676c887fb955624e658e3823,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
2,1780783756,2026-06-06T22:09:16Z,88052514,0x75e9c920a369d446b4a8d350d5b1c25b1dc63c39304fa9bd607bf81571f1a766,328,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0xdc5cb48aa552995edb952bf2b0434df01e20808a,token2,USDC,SELL,BUY,0.970,1.940000,2.000000,0.00000,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
3,1780783756,2026-06-06T22:09:16Z,88052514,0x75e9c920a369d446b4a8d350d5b1c25b1dc63c39304fa9bd607bf81571f1a766,330,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xdc5cb48aa552995edb952bf2b0434df01e20808a,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token2,BUY,SELL,0.970,1.940000,2.000000,0.00407,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x72685190475bb1cde27664f511be30d53b2480c98603b0bc96565de5351a6853,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
4,1780783756,2026-06-06T22:09:16Z,88052514,0xd8b15166989fe01858f90a81798ae183ee70a25c620197b18397c5281b30005a,336,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x16bc7faccdb6dedd07d47333a6f06fef635dd23a,token2,USDC,SELL,BUY,0.970,21.825000,22.500000,0.00000,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
5,1780783756,2026-06-06T22:09:16Z,88052514,0xd8b15166989fe01858f90a81798ae183ee70a25c620197b18397c5281b30005a,338,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0x16bc7faccdb6dedd07d47333a6f06fef635dd23a,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token2,BUY,SELL,0.970,21.825000,22.500000,0.04583,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x3e2309f4eaa78cd7789f991f936ff6b8de3465529c3fc8777d13c71b02e79aab,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
6,1780783756,2026-06-06T22:09:16Z,88052514,0xe1db1908adb3bd175eb4cdc15549f31b680fc6b9f366e672ed97e8a2c0460786,344,CTF_EXCHANGE_V2,v2,563572,eth-updown-5m-1780783500,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",2448220,0x1eb6352998233b4a191a8d30ac54e6fe73f07992d4b47d2085b2e0511eedfa40,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",token1,Up,0x98da26e8fa92fc7973af6f95baf5efc4e2493b56,0x674887d1ac838099a48b629dff53f25b7b87ee08,USDC,token1,BUY,SELL,0.100,0.430000,4.300000,0.00000,114452155101132071341035941016658939783020858202809214057500414093543091573082,0x04e8f45e8ed3662347b2b8686c3ed9dfad1b6d247b70795d05bcc0ca5580d51c,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
7,1780783756,2026-06-06T22:09:16Z,88052514,0xe1db1908adb3bd175eb4cdc15549f31b680fc6b9f366e672ed97e8a2c0460786,347,CTF_EXCHANGE_V2,v2,563572,eth-updown-5m-1780783500,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",2448220,0x1eb6352998233b4a191a8d30ac54e6fe73f07992d4b47d2085b2e0511eedfa40,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",token1,Up,0x674887d1ac838099a48b629dff53f25b7b87ee08,0xe111180000d2663c0091e4f400237545b87b996b,token1,USDC,SELL,BUY,0.100,0.430000,4.300000,0.02709,114452155101132071341035941016658939783020858202809214057500414093543091573082,0xd0785400d1a717277872e0f3a70fc60b717c25afc19709bf1442f50d6951ea38,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
8,1780783756,2026-06-06T22:09:16Z,88052514,0x5ac0f5ea6c01482e4aacd7f2259ca54727ee7b98ee9fd048e0694fbdba64024a,353,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0xf898c9739a8b6ae576f4efcadf7241a64b49fffc,token2,USDC,SELL,BUY,0.970,58.200000,60.000000,0.00000,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
9,1780783756,2026-06-06T22:09:16Z,88052514,0x5ac0f5ea6c01482e4aacd7f2259ca54727ee7b98ee9fd048e0694fbdba64024a,355,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xf898c9739a8b6ae576f4efcadf7241a64b49fffc,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token2,BUY,SELL,0.970,58.200000,60.000000,0.12222,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4c7f5aa2d0d5316a135d39e7176f304352af219a47dd60a56bab6c146aef034e,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
10,1780783756,2026-06-06T22:09:16Z,88052514,0x726666827b35fdaf692982fc61c085fe3fee2bee5cf01a973a0b64425109c375,372,CTF_EXCHANGE_V2,v2,565556,lol-kt-dk-2026-06-07,LoL: KT Rolster vs Dplus KIA (BO5) - LCK Road to MSI,2453470,0x1cd6790426a19dff12d911967be5719a09af77ae1a3f68cdc848f5106ea3c78c,Games Total: O/U 4.5,token1,Over,0x098c8fe3e2e915715e8b4c013ad43b433ca21c67,0x2b9c090d15f1c94d44a81c4880de6f3a8b078927,USDC,token1,BUY,SELL,0.330,7.260000,22.000000,0.00000,23072918760322003953834133091938577549710981434898330780243901892346723175335,0x6e24f356067594bc5320e635150d882cfca6055c88d3f0f3ac245180d82befd9,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
11,1780783756,2026-06-06T22:09:16Z,88052514,0x726666827b35fdaf692982fc61c085fe3fee2bee5cf01a973a0b64425109c375,376,CTF_EXCHANGE_V2,v2,565556,lol-kt-dk-2026-06-07,LoL: KT Rolster vs Dplus KIA (BO5) - LCK Road to MSI,2453470,0x1cd6790426a19dff12d911967be5719a09af77ae1a3f68cdc848f5106ea3c78c,Games Total: O/U 4.5,token2,Under,0x2b9c090d15f1c94d44a81c4880de6f3a8b078927,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token2,BUY,SELL,0.670,14.740000,22.000000,0.14592,93875522406881330816662731472890482041551054506856307552246473115634975932107,0x03bb34d56033706ed42784e64f4451f0120c1237d8812912b0727a0e48d88225,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
12,1780783756,2026-06-06T22:09:16Z,88052514,0xabaf3ab1a18f096b20caffa8428371cd7b0cad32f95cec8f54c15042f6830307,381,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x0448f9df3a55876f234245e59e288b740cd486d9,token2,USDC,SELL,BUY,0.970,4.999998,5.154638,0.00000,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
13,1780783756,2026-06-06T22:09:16Z,88052514,0xabaf3ab1a18f096b20caffa8428371cd7b0cad32f95cec8f54c15042f6830307,383,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0x0448f9df3a55876f234245e59e288b740cd486d9,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token2,BUY,SELL,0.970,4.999998,5.154638,0.01050,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x3fbc2db611d9e7372d2c279e793c73b72504b9fd3b9b7e15295f6b5690ea613a,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
14,1780783756,2026-06-06T22:09:16Z,88052514,0xc7a7e4a0d7569003b6bf089706dd76404f4afa02db9e567fe85b67e4ce790136,389,CTF_EXCHANGE_V2,v2,563560,btc-updown-15m-1780783200,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",token1,Up,0x2ed94d1a460379292d2e3b46f2cf7d94b033f271,0xed89b210faa8d83a0484291b8c06b5d717dddf85,USDC,token1,BUY,SELL,0.050,0.200000,4.000000,0.00000,7705923800682500862272350897127800049020938240555080668886595577732534640441,0xc9961bf673e3db49834a0e7890e8dbd349af63a9ef3cf3e7fd453757ae743e9f,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
15,1780783756,2026-06-06T22:09:16Z,88052514,0xc7a7e4a0d7569003b6bf089706dd76404f4afa02db9e567fe85b67e4ce790136,392,CTF_EXCHANGE_V2,v2,563560,btc-updown-15m-1780783200,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",token1,Up,0xed89b210faa8d83a0484291b8c06b5d717dddf85,0xe111180000d2663c0091e4f400237545b87b996b,token1,USDC,SELL,BUY,0.050,0.200000,4.000000,0.01330,7705923800682500862272350897127800049020938240555080668886595577732534640441,0xc8fab0ab448391dcc5068e43ee917f60f8fcc212820590014b93351faed0186c,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
16,1780783756,2026-06-06T22:09:16Z,88052514,0xadd7ac69089bbd5faf4042044bb7511034d907090ff20450874a9cbf14ebdead,455,CTF_EXCHANGE_V2,v2,102007,spacex-ipo-closing-market-cap-above,SpaceX IPO closing market cap above ___ ?,2308003,0x2576d8fe9a5ed75f58c2ef34bad961916d4799254c8d248734aee5cf5224eb07,SpaceX IPO closing market cap above $4T?,token2,No,0x93511d72d294f1478739bc38f578bf0306fd9e4d,0xd83df2a0ed02e608a5d4bc8d4bf4b322f4fb4678,USDC,token2,BUY,SELL,0.992,248.000000,250.000000,0.00000,79503879558000863984423353516801517784351760207093629712308932082454207172191,0xa7fe2b76a68fa24a12e9c12b8db97f35c3f4eb2e650e1ad649ef817e0270c689,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
17,1780783756,2026-06-06T22:09:16Z,88052514,0xadd7ac69089bbd5faf4042044bb7511034d907090ff20450874a9cbf14ebdead,459,CTF_EXCHANGE_V2,v2,102007,spacex-ipo-closing-market-cap-above,SpaceX IPO closing market cap above ___ ?,2308003,0x2576d8fe9a5ed75f58c2ef34bad961916d4799254c8d248734aee5cf5224eb07,SpaceX IPO closing market cap above $4T?,token1,Yes,0xd83df2a0ed02e608a5d4bc8d4bf4b322f4fb4678,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token1,BUY,SELL,0.008,2.000000,250.000000,0.07936,25759554244493354767227852844420516405380702219740675120053478060935865126097,0x8c8649fc767dc2cd11a4773ba5954d5511018d4c505606bcb3eeb66f5bc71792,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
18,1780783756,2026-06-06T22:09:16Z,88052514,0x61a8014d845c72de25723c80c148d72ddcd5ad1f10396fc968cef137fc39c335,487,CTF_EXCHANGE_V2,v2,563569,sol-updown-5m-1780783500,"Solana Up or Down - June 6, 6:05PM-6:10PM ET",2448218,0xc631da5e715fb796c2195d44d23cbf5c1fece8249cab544cd90a9b0513859001,"Solana Up or Down - June 6, 6:05PM-6:10PM ET",token1,Up,0xbf17c1643131948cc5aecb890e915b124e7540be,0x9919a655c2694462950d9ca5a0307202740a0a5d,USDC,token1,BUY,SELL,0.090,0.181978,2.021977,0.00000,41686662825191984631745612539353248083087678877167731994748991779176910374012,0xc35bab3257e18c6312a4657b9608cb5fad5d0b687fcda73924cb9b0e2e9e70bc,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
19,1780783756,2026-06-06T22:09:16Z,88052514,0x61a8014d845c72de25723c80c148d72ddcd5ad1f10396fc968cef137fc39c335,491,CTF_EXCHANGE_V2,v2,563569,sol-updown-5m-1780783500,"Solana Up or Down - June 6, 6:05PM-6:10PM ET",2448218,0xc631da5e715fb796c2195d44d23cbf5c1fece8249cab544cd90a9b0513859001,"Solana Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0x9919a655c2694462950d9ca5a0307202740a0a5d,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token2,BUY,SELL,0.910,1.839999,2.021977,0.01159,59879328752383442614140229014234327720098339084993477538503772314944394059012,0xc16c37f0cd427182318529901010eefeb0cfd792a950dd498db1902799c8745e,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
20,1780783756,2026-06-06T22:09:16Z,88052514,0xd72d00b58060e81a4ba1f9c83e0b39fd60a15235c03c1c732768459f12afda24,496,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x5e2b9261b0c4f697b55bf921ff2bc227183d9101,token2,USDC,SELL,BUY,0.970,42.569998,43.886596,0.00000,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
21,1780783756,2026-06-06T22:09:16Z,88052514,0xd72d00b58060e81a4ba1f9c83e0b39fd60a15235c03c1c732768459f12afda24,498,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0x5e2b9261b0c4f697b55bf921ff2bc227183d9101,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token2,BUY,SELL,0.970,42.569998,43.886596,0.08939,106870947731841299226931869706163862462989258483960759258537831115103115928870,0xb33e5418a787c416aa15de572c8ddca64a5f1100736287203e94482de93f8b53,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
22,1780783756,2026-06-06T22:09:16Z,88052514,0xeffd8c5133fd6a53304344114ed2068ff45d0df9ea990a6649fbab7aa2fcb9d0,504,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x75cc3b63a2f2423085e10706c78b494017b93ce1,token2,USDC,SELL,BUY,0.970,41.579998,42.865978,0.00000,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
23,1780783756,2026-06-06T22:09:16Z,88052514,0xeffd8c5133fd6a53304344114ed2068ff45d0df9ea990a6649fbab7aa2fcb9d0,506,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0x75cc3b63a2f2423085e10706c78b494017b93ce1,0xe111180000d2663c0091e4f400237545b87b996b,USDC,token2,BUY,SELL,0.970,41.579998,42.865978,0.08731,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x28df76940fcb29e8b83387647a86719e81b1436c9497b962530f9aacc591eb08,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
24,1780783756,2026-06-06T22:09:16Z,88052514,0x36186d66faa05f93b4734edf3add4e9e855905ae0ca306cb28d2a9e1f2abe5e3,512,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token2,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x2aa856f784c08331aeac414e3bf4df22440609b0,token2,USDC,SELL,BUY,0.970,39.879998,41.113401,0.00000,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000

  contract_generation                 contract maker_direction nonusdc_side  rows   usd_amount  avg_price
1                  v2          CTF_EXCHANGE_V2             BUY       token2    99  3008.392592   0.858606
0                  v2          CTF_EXCHANGE_V2             BUY       token1    52   956.625227   0.239545
3                  v2          CTF_EXCHANGE_V2            SELL       token2    52  1260.856602   0.959558
4                  v2  NEGRISK_CTF_EXCHANGE_V2             BUY       token1    15   357.093163   0.323185
2                  v2          CTF_EXCHANGE_V2            SELL       token1    14   319.911289   0.189143
5                  v2  NEGRISK_CTF_EXCHANGE_V2             BUY       token2    13   183.154780   0.765590
6                  v2  NEGRISK_CTF_EXCHANGE_V2            SELL       token1     4   335.354740   0.301250
7                  v2  NEGRISK_CTF_EXCHANGE_V2            SELL       token2     1     0.408360   0.996000

## Quant view

`quant` removes rows where the taker is an exchange contract intermediary and flips token2 prices into token1 perspective. After this step, `price` is comparable across binary markets as the token1/Yes-side price.

In [7]:
quant = sample["quant"]
display(quant.head(30))

if not quant.empty:
    display(
        quant.groupby(["event_slug", "market_id"], dropna=False)
        .agg(rows=("transaction_hash", "count"), usd_amount=("usd_amount", "sum"), min_price=("price", "min"), max_price=("price", "max"))
        .reset_index()
        .sort_values("rows", ascending=False)
        .head(20)
    )

,timestamp,datetime,block_number,transaction_hash,log_index,contract,contract_generation,event_id,event_slug,event_title,market_id,condition_id,question,nonusdc_side,answer,maker,taker,maker_asset,taker_asset,maker_direction,taker_direction,price,usd_amount,token_amount,fee_amount,asset_id,order_hash,builder,metadata
0,1780783756,2026-06-06T22:09:16Z,88052514,0x8d8f5f7d15e8d55860604830df7edf1af816bdaa21ea95036f9c0e7d16933218,319,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xcaad1b3a62d286214f94ace993a1e80e44aa255c,0xfd16bdd047ecdb6c006a9f159c14c8bbb7462c91,USDC,token2,BUY,SELL,0.040,46.627200,48.570000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x1f2b120d52d2bbfbd2ff8ef5886c9134719b33008407f696d97e577bbb33d8d2,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
1,1780783756,2026-06-06T22:09:16Z,88052514,0x75e9c920a369d446b4a8d350d5b1c25b1dc63c39304fa9bd607bf81571f1a766,328,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0xdc5cb48aa552995edb952bf2b0434df01e20808a,token2,USDC,SELL,BUY,0.030,1.940000,2.000000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
2,1780783756,2026-06-06T22:09:16Z,88052514,0xd8b15166989fe01858f90a81798ae183ee70a25c620197b18397c5281b30005a,336,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x16bc7faccdb6dedd07d47333a6f06fef635dd23a,token2,USDC,SELL,BUY,0.030,21.825000,22.500000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
3,1780783756,2026-06-06T22:09:16Z,88052514,0xe1db1908adb3bd175eb4cdc15549f31b680fc6b9f366e672ed97e8a2c0460786,344,CTF_EXCHANGE_V2,v2,563572,eth-updown-5m-1780783500,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",2448220,0x1eb6352998233b4a191a8d30ac54e6fe73f07992d4b47d2085b2e0511eedfa40,"Ethereum Up or Down - June 6, 6:05PM-6:10PM ET",token1,Up,0x98da26e8fa92fc7973af6f95baf5efc4e2493b56,0x674887d1ac838099a48b629dff53f25b7b87ee08,USDC,token1,BUY,SELL,0.100,0.430000,4.300000,0.0,114452155101132071341035941016658939783020858202809214057500414093543091573082,0x04e8f45e8ed3662347b2b8686c3ed9dfad1b6d247b70795d05bcc0ca5580d51c,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
4,1780783756,2026-06-06T22:09:16Z,88052514,0x5ac0f5ea6c01482e4aacd7f2259ca54727ee7b98ee9fd048e0694fbdba64024a,353,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0xf898c9739a8b6ae576f4efcadf7241a64b49fffc,token2,USDC,SELL,BUY,0.030,58.200000,60.000000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
5,1780783756,2026-06-06T22:09:16Z,88052514,0x726666827b35fdaf692982fc61c085fe3fee2bee5cf01a973a0b64425109c375,372,CTF_EXCHANGE_V2,v2,565556,lol-kt-dk-2026-06-07,LoL: KT Rolster vs Dplus KIA (BO5) - LCK Road to MSI,2453470,0x1cd6790426a19dff12d911967be5719a09af77ae1a3f68cdc848f5106ea3c78c,Games Total: O/U 4.5,token1,Over,0x098c8fe3e2e915715e8b4c013ad43b433ca21c67,0x2b9c090d15f1c94d44a81c4880de6f3a8b078927,USDC,token1,BUY,SELL,0.330,7.260000,22.000000,0.0,23072918760322003953834133091938577549710981434898330780243901892346723175335,0x6e24f356067594bc5320e635150d882cfca6055c88d3f0f3ac245180d82befd9,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
6,1780783756,2026-06-06T22:09:16Z,88052514,0xabaf3ab1a18f096b20caffa8428371cd7b0cad32f95cec8f54c15042f6830307,381,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x0448f9df3a55876f234245e59e288b740cd486d9,token2,USDC,SELL,BUY,0.030,4.999998,5.154638,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
7,1780783756,2026-06-06T22:09:16Z,88052514,0xc7a7e4a0d7569003b6bf089706dd76404f4afa02db9e567fe85b67e4ce790136,389,CTF_EXCHANGE_V2,v2,563560,btc-updown-15m-1780783200,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",token1,Up,0x2ed94d1a460379292d2e3b46f2cf7d94b033f271,0xed89b210faa8d83a0484291b8c06b5d717dddf85,USDC,token1,BUY,SELL,0.050,0.200000,4.000000,0.0,7705923800682500862272350897127800049020938240555080668886595577732534640441,0xc9961bf673e3db49834a0e7890e8dbd349af63a9ef3cf3e7fd453757ae743e9f,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
8,1780783756,2026-06-06T22:09:16Z,88052514,0xadd7ac69089bbd5faf4042044bb7511034d907090ff20450874a9cbf14ebdead,455,CTF_EXCHANGE_V2,v2,102007,spacex-ipo-closing-market-cap-above,SpaceX IPO closing market cap above ___ ?,2308003,0x2576d8fe9a5ed75f58c2ef34bad961916d4799254c8d248734aee5cf5224eb07,SpaceX IPO closing market cap above $4T?,token1,No,0x93511d72d294f1478739bc38f578bf0306fd9e4d,0xd83df2a0ed02e608a5d4bc8d4bf4b322f4fb4678,USDC,token2,BUY,SELL,0.008,248.000000,250.000000,0.0,79503879558000863984423353516801517784351760207093629712308932082454207172191,0xa7fe2b76a68fa24a12e9c12b8db97f35c3f4eb2e650e1ad649ef817e0270c689,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
9,1780783756,2026-06-06T22:09:16Z,88052514,0x61a8014d845c72de25723c80c148d72ddcd5ad1f10396fc968cef137fc39c335,487,CTF_EXCHANGE_V2,v2,563569,sol-updown-5m-1780783500,"Solana Up or Down - June 6, 6:05PM-6:10PM ET",2448218,0xc631da5e715fb796c2195d44d23cbf5c1fece8249cab544cd90a9b0513859001,"Solana Up or Down - June 6, 6:05PM-6:10PM ET",token1,Up,0xbf17c1643131948cc5aecb890e915b124e7540be,0x9919a655c2694462950d9ca5a0307202740a0a5d,USDC,token1,BUY,SELL,0.090,0.181978,2.021977,0.0,41686662825191984631745612539353248083087678877167731994748991779176910374012,0xc35bab3257e18c6312a4657b9608cb5fad5d0b687fcda73924cb9b0e2e9e70bc,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
10,1780783756,2026-06-06T22:09:16Z,88052514,0xd72d00b58060e81a4ba1f9c83e0b39fd60a15235c03c1c732768459f12afda24,496,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x5e2b9261b0c4f697b55bf921ff2bc227183d9101,token2,USDC,SELL,BUY,0.030,42.569998,43.886596,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
11,1780783756,2026-06-06T22:09:16Z,88052514,0xeffd8c5133fd6a53304344114ed2068ff45d0df9ea990a6649fbab7aa2fcb9d0,504,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x75cc3b63a2f2423085e10706c78b494017b93ce1,token2,USDC,SELL,BUY,0.030,41.579998,42.865978,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
12,1780783756,2026-06-06T22:09:16Z,88052514,0x36186d66faa05f93b4734edf3add4e9e855905ae0ca306cb28d2a9e1f2abe5e3,512,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x2aa856f784c08331aeac414e3bf4df22440609b0,token2,USDC,SELL,BUY,0.030,39.879998,41.113401,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
13,1780783756,2026-06-06T22:09:16Z,88052514,0x3ac6c0ddc74ebeb438cd2721a893c11648736946513ba229f5b11a5acd9ef41d,532,CTF_EXCHANGE_V2,v2,563560,btc-updown-15m-1780783200,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",token1,Up,0x4e9e2920eb43c30e04c92843f101d8ca10dfa165,0x712be8f7388a7ac628e835463c48ffb6a40e100d,USDC,token1,BUY,SELL,0.050,1.494500,29.890000,0.0,7705923800682500862272350897127800049020938240555080668886595577732534640441,0x5924a1cfab4b75f3fdbbb53bb26a5f7e128436fe6919744b27fc4577773a9fc0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
14,1780783756,2026-06-06T22:09:16Z,88052514,0x3ac6c0ddc74ebeb438cd2721a893c11648736946513ba229f5b11a5acd9ef41d,534,CTF_EXCHANGE_V2,v2,563560,btc-updown-15m-1780783200,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,"Bitcoin Up or Down - June 6, 6:00PM-6:15PM ET",token1,Up,0x1327e266fc9be1633a355b6d71206eeb9ce30119,0x712be8f7388a7ac628e835463c48ffb6a40e100d,USDC,token1,BUY,SELL,0.050,0.850500,17.010000,0.0,7705923800682500862272350897127800049020938240555080668886595577732534640441,0x577a14a22bcbec449710b34f440605e382a821db7431d6a1806976e54981945e,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
15,1780783756,2026-06-06T22:09:16Z,88052514,0xe5d97f15de344ced79dad54427e13d36929991381c030011cbfe2f6657d92f5f,554,CTF_EXCHANGE_V2,v2,562243,cs2-abyssa-dingcu-2026-06-08,Counter-Strike: Abyssal vs Ding Cuts (BO3) - Dfrag Open Series #5 Group A,2444063,0x48f888418459478da09d2f2fa2b1d609b6d72498a13bd683ee844039f35f2675,Counter-Strike: Abyssal vs Ding Cuts (BO3) - Dfrag Open Series #5 Group A,token1,Abyssal,0x521070c99db06e54af5e8e4a91d6858decdfbd53,0x4db1bd6c5436eb1ef295c660c1d88d3c6c52528c,USDC,token1,BUY,SELL,0.500,2.000000,4.000000,0.0,110669970070373132655248461102832810138230744419178258353211648391397556926754,0x9633ddbfb2bd4b07868244b59702be196faf497b0c18193247c730ad20de76af,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
16,1780783756,2026-06-06T22:09:16Z,88052514,0x179ab8a439cc65e0b2519b4a1550750de707ab040b7cd7c4130586ee4f11534e,563,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0xcdec78fa872e1771bcba800b74cc1aa565d15102,token2,USDC,SELL,BUY,0.030,7.760000,8.000000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
17,1780783756,2026-06-06T22:09:16Z,88052514,0xec07377ee6fc6c9b73da2f05ba0180bdc31bdc8e6bd82fe3f7f6d5180f5fa0c8,571,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0x580dbe563496d8c57c8c724f761c9ca4b02ccfb5,token2,USDC,SELL,BUY,0.030,1.959998,2.020617,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
18,1780783756,2026-06-06T22:09:16Z,88052514,0x230a7d81eb345da2931fc66d4b7c41dba003e29cfd6a0e68142c49bad82d792b,579,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,0xecfa588c316e9edb58e9730a1b8d8db757577fe0,token2,USDC,SELL,BUY,0.030,97.970000,101.000000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x4be39b32fea472c4cff5378bde1493c457a8793df7a0292a09ba4fd86046b6fa,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
19,1780783756,2026-06-06T22:09:16Z,88052514,0xef1a05c099d5f23e11d0269872540d87f1160ff17ec77959d46556154df3d89b,610,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0x2855555a48ee7ec2e67272701651bfe77034ebe8,0xb41c082290933df8904699cf67895d60ffd95bd3,USDC,token2,BUY,SELL,0.040,113.606400,118.340000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x3610dbd321d7e7d85995b3b9c76cc929e08dea71daad3242583134fc1b9c4bf0,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
20,1780783756,2026-06-06T22:09:16Z,88052514,0xef1a05c099d5f23e11d0269872540d87f1160ff17ec77959d46556154df3d89b,612,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0x2855555a48ee7ec2e67272701651bfe77034ebe8,0xb41c082290933df8904699cf67895d60ffd95bd3,USDC,token2,BUY,SELL,0.040,45.120000,47.000000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x5cde24dfda463d9dccb6514a1fcac26c8eed42fa4187bde5aaeea5e55f6a158e,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
21,1780783756,2026-06-06T22:09:16Z,88052514,0xef1a05c099d5f23e11d0269872540d87f1160ff17ec77959d46556154df3d89b,614,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0x9d57c42e847173d06841703825d3fe2299e456ea,0xb41c082290933df8904699cf67895d60ffd95bd3,USDC,token2,BUY,SELL,0.040,9.600000,10.000000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0xd2299a17736407a695bc4542de6acd3d7de4a1c293b4b32b0d77097115dfaf05,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
22,1780783756,2026-06-06T22:09:16Z,88052514,0xef1a05c099d5f23e11d0269872540d87f1160ff17ec77959d46556154df3d89b,616,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xdf7930e89a2c47560165331863c31deca0733dcd,0xb41c082290933df8904699cf67895d60ffd95bd3,USDC,token2,BUY,SELL,0.040,14.400000,15.000000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x392d8d16539cc8ebc4237a9a07321bffe10f27ebcaec491380e5197a5ef3114c,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
23,1780783756,2026-06-06T22:09:16Z,88052514,0xef1a05c099d5f23e11d0269872540d87f1160ff17ec77959d46556154df3d89b,618,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0x3989712e9850ed88fc33ac17fb56a52f1286d601,0xb41c082290933df8904699cf67895d60ffd95bd3,USDC,token2,BUY,SELL,0.040,16.003200,16.670000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x9dd381571d4d618a2263c0b6c1a880221fd025959874b44da4cdec33ac0615ec,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000
24,1780783756,2026-06-06T22:09:16Z,88052514,0xef1a05c099d5f23e11d0269872540d87f1160ff17ec77959d46556154df3d89b,620,CTF_EXCHANGE_V2,v2,563571,btc-updown-5m-1780783500,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,"Bitcoin Up or Down - June 6, 6:05PM-6:10PM ET",token1,Down,0xbf337426aa856996b8bb79b238345dd1a0276bf7,0xb41c082290933df8904699cf67895d60ffd95bd3,USDC,token2,BUY,SELL,0.040,28.800000,30.000000,0.0,106870947731841299226931869706163862462989258483960759258537831115103115928870,0x9256f8cccc11d3a142baa5566aeb1a3d13ee867bb619108329c3b5d409945e07,0x0000000000000000000000000000000000000000000000000000000000000000,0x0000000000000000000000000000000000000000000000000000000000000000

                                     event_slug market_id  rows   usd_amount  min_price  max_price
4                      btc-updown-5m-1780783500   2448221    59  1776.516063      0.030      0.040
3                     btc-updown-15m-1780783200   2448208    12     5.295000      0.050      0.050
8                      eth-updown-5m-1780783500   2448220    10     3.124509      0.090      0.100
17                       lol-fly-tl2-2026-06-06   2407743     8   611.795900      0.430      0.440
14  highest-temperature-in-paris-on-june-8-2026   2456146     8    22.210000      0.210      0.250
15  highest-temperature-in-paris-on-june-8-2026   2456148     7    14.877048      0.270      0.280
30            xrp-up-or-down-june-6-2026-6pm-et   2438947     4    26.395700      0.260      0.270
32                     xrp-updown-5m-1780783800   2448231     3     5.672000      0.520      0.540
24                     will-alberta-join-the-us   1345724     2     7.991400      0.047      0.047
22                        ufc-bru-ed-2026-06-06   2280037     2   174.857142      0.510      0.510
13                       fif-qat-slv-2026-06-06   2222122     2   305.999100      0.990      0.990
26        will-spacexs-valuation-hit-by-june-30   2298908     2    24.927030      0.073      0.073
20                     sol-updown-5m-1780783500   2448218     2     0.499678      0.090      0.090
28                      wnba-ind-nyl-2026-06-06   2441635     2   100.549999      0.520      0.520
31                     xrp-updown-5m-1780783500   2448222     2     0.499963      0.120      0.120
25         will-jesus-christ-return-before-2027    703258     1     0.999999      0.021      0.021
27  will-trump-publicly-insult-someone-onptptpt   2412314     1     0.052631      0.950      0.950
23                      ufc-pri-che3-2026-06-06   2280111     1    96.721428      0.440      0.440
29                             world-cup-winner    558958     1    27.464000      0.001      0.001
21          spacex-ipo-closing-market-cap-above   2308003     1   248.000000      0.008      0.008

## Users view

`users` expands each cleaned trade into two participant rows: one for maker and one for taker. Sells are represented as negative token amounts, and direction is normalized to `BUY`, matching the established project's user-level convention.

In [8]:
users = sample["users"]
display(users.head(40))

if not users.empty:
    display(
        users.groupby(["user", "role"], dropna=False)
        .agg(rows=("transaction_hash", "count"), net_tokens=("token_amount", "sum"), usd_amount=("usd_amount", "sum"))
        .reset_index()
        .sort_values("rows", ascending=False)
        .head(20)
    )

,timestamp,datetime,block_number,transaction_hash,event_id,market_id,condition_id,user,role,price,token_amount,usd_amount
0,1780783756,2026-06-06T22:09:16Z,88052514,0x8d8f5f7d15e8d55860604830df7edf1af816bdaa21ea95036f9c0e7d16933218,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xcaad1b3a62d286214f94ace993a1e80e44aa255c,maker,0.040,48.570000,46.627200
1,1780783756,2026-06-06T22:09:16Z,88052514,0x8d8f5f7d15e8d55860604830df7edf1af816bdaa21ea95036f9c0e7d16933218,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xfd16bdd047ecdb6c006a9f159c14c8bbb7462c91,taker,0.040,-48.570000,46.627200
2,1780783756,2026-06-06T22:09:16Z,88052514,0x75e9c920a369d446b4a8d350d5b1c25b1dc63c39304fa9bd607bf81571f1a766,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-2.000000,1.940000
3,1780783756,2026-06-06T22:09:16Z,88052514,0x75e9c920a369d446b4a8d350d5b1c25b1dc63c39304fa9bd607bf81571f1a766,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xdc5cb48aa552995edb952bf2b0434df01e20808a,taker,0.030,2.000000,1.940000
4,1780783756,2026-06-06T22:09:16Z,88052514,0xd8b15166989fe01858f90a81798ae183ee70a25c620197b18397c5281b30005a,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-22.500000,21.825000
5,1780783756,2026-06-06T22:09:16Z,88052514,0xd8b15166989fe01858f90a81798ae183ee70a25c620197b18397c5281b30005a,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0x16bc7faccdb6dedd07d47333a6f06fef635dd23a,taker,0.030,22.500000,21.825000
6,1780783756,2026-06-06T22:09:16Z,88052514,0xe1db1908adb3bd175eb4cdc15549f31b680fc6b9f366e672ed97e8a2c0460786,563572,2448220,0x1eb6352998233b4a191a8d30ac54e6fe73f07992d4b47d2085b2e0511eedfa40,0x98da26e8fa92fc7973af6f95baf5efc4e2493b56,maker,0.100,4.300000,0.430000
7,1780783756,2026-06-06T22:09:16Z,88052514,0xe1db1908adb3bd175eb4cdc15549f31b680fc6b9f366e672ed97e8a2c0460786,563572,2448220,0x1eb6352998233b4a191a8d30ac54e6fe73f07992d4b47d2085b2e0511eedfa40,0x674887d1ac838099a48b629dff53f25b7b87ee08,taker,0.100,-4.300000,0.430000
8,1780783756,2026-06-06T22:09:16Z,88052514,0x5ac0f5ea6c01482e4aacd7f2259ca54727ee7b98ee9fd048e0694fbdba64024a,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-60.000000,58.200000
9,1780783756,2026-06-06T22:09:16Z,88052514,0x5ac0f5ea6c01482e4aacd7f2259ca54727ee7b98ee9fd048e0694fbdba64024a,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xf898c9739a8b6ae576f4efcadf7241a64b49fffc,taker,0.030,60.000000,58.200000
10,1780783756,2026-06-06T22:09:16Z,88052514,0x726666827b35fdaf692982fc61c085fe3fee2bee5cf01a973a0b64425109c375,565556,2453470,0x1cd6790426a19dff12d911967be5719a09af77ae1a3f68cdc848f5106ea3c78c,0x098c8fe3e2e915715e8b4c013ad43b433ca21c67,maker,0.330,22.000000,7.260000
11,1780783756,2026-06-06T22:09:16Z,88052514,0x726666827b35fdaf692982fc61c085fe3fee2bee5cf01a973a0b64425109c375,565556,2453470,0x1cd6790426a19dff12d911967be5719a09af77ae1a3f68cdc848f5106ea3c78c,0x2b9c090d15f1c94d44a81c4880de6f3a8b078927,taker,0.330,-22.000000,7.260000
12,1780783756,2026-06-06T22:09:16Z,88052514,0xabaf3ab1a18f096b20caffa8428371cd7b0cad32f95cec8f54c15042f6830307,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-5.154638,4.999998
13,1780783756,2026-06-06T22:09:16Z,88052514,0xabaf3ab1a18f096b20caffa8428371cd7b0cad32f95cec8f54c15042f6830307,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0x0448f9df3a55876f234245e59e288b740cd486d9,taker,0.030,5.154638,4.999998
14,1780783756,2026-06-06T22:09:16Z,88052514,0xc7a7e4a0d7569003b6bf089706dd76404f4afa02db9e567fe85b67e4ce790136,563560,2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,0x2ed94d1a460379292d2e3b46f2cf7d94b033f271,maker,0.050,4.000000,0.200000
15,1780783756,2026-06-06T22:09:16Z,88052514,0xc7a7e4a0d7569003b6bf089706dd76404f4afa02db9e567fe85b67e4ce790136,563560,2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,0xed89b210faa8d83a0484291b8c06b5d717dddf85,taker,0.050,-4.000000,0.200000
16,1780783756,2026-06-06T22:09:16Z,88052514,0xadd7ac69089bbd5faf4042044bb7511034d907090ff20450874a9cbf14ebdead,102007,2308003,0x2576d8fe9a5ed75f58c2ef34bad961916d4799254c8d248734aee5cf5224eb07,0x93511d72d294f1478739bc38f578bf0306fd9e4d,maker,0.008,250.000000,248.000000
17,1780783756,2026-06-06T22:09:16Z,88052514,0xadd7ac69089bbd5faf4042044bb7511034d907090ff20450874a9cbf14ebdead,102007,2308003,0x2576d8fe9a5ed75f58c2ef34bad961916d4799254c8d248734aee5cf5224eb07,0xd83df2a0ed02e608a5d4bc8d4bf4b322f4fb4678,taker,0.008,-250.000000,248.000000
18,1780783756,2026-06-06T22:09:16Z,88052514,0x61a8014d845c72de25723c80c148d72ddcd5ad1f10396fc968cef137fc39c335,563569,2448218,0xc631da5e715fb796c2195d44d23cbf5c1fece8249cab544cd90a9b0513859001,0xbf17c1643131948cc5aecb890e915b124e7540be,maker,0.090,2.021977,0.181978
19,1780783756,2026-06-06T22:09:16Z,88052514,0x61a8014d845c72de25723c80c148d72ddcd5ad1f10396fc968cef137fc39c335,563569,2448218,0xc631da5e715fb796c2195d44d23cbf5c1fece8249cab544cd90a9b0513859001,0x9919a655c2694462950d9ca5a0307202740a0a5d,taker,0.090,-2.021977,0.181978
20,1780783756,2026-06-06T22:09:16Z,88052514,0xd72d00b58060e81a4ba1f9c83e0b39fd60a15235c03c1c732768459f12afda24,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-43.886596,42.569998
21,1780783756,2026-06-06T22:09:16Z,88052514,0xd72d00b58060e81a4ba1f9c83e0b39fd60a15235c03c1c732768459f12afda24,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0x5e2b9261b0c4f697b55bf921ff2bc227183d9101,taker,0.030,43.886596,42.569998
22,1780783756,2026-06-06T22:09:16Z,88052514,0xeffd8c5133fd6a53304344114ed2068ff45d0df9ea990a6649fbab7aa2fcb9d0,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-42.865978,41.579998
23,1780783756,2026-06-06T22:09:16Z,88052514,0xeffd8c5133fd6a53304344114ed2068ff45d0df9ea990a6649fbab7aa2fcb9d0,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0x75cc3b63a2f2423085e10706c78b494017b93ce1,taker,0.030,42.865978,41.579998
24,1780783756,2026-06-06T22:09:16Z,88052514,0x36186d66faa05f93b4734edf3add4e9e855905ae0ca306cb28d2a9e1f2abe5e3,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-41.113401,39.879998
25,1780783756,2026-06-06T22:09:16Z,88052514,0x36186d66faa05f93b4734edf3add4e9e855905ae0ca306cb28d2a9e1f2abe5e3,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0x2aa856f784c08331aeac414e3bf4df22440609b0,taker,0.030,41.113401,39.879998
26,1780783756,2026-06-06T22:09:16Z,88052514,0x3ac6c0ddc74ebeb438cd2721a893c11648736946513ba229f5b11a5acd9ef41d,563560,2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,0x4e9e2920eb43c30e04c92843f101d8ca10dfa165,maker,0.050,29.890000,1.494500
27,1780783756,2026-06-06T22:09:16Z,88052514,0x3ac6c0ddc74ebeb438cd2721a893c11648736946513ba229f5b11a5acd9ef41d,563560,2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,0x712be8f7388a7ac628e835463c48ffb6a40e100d,taker,0.050,-29.890000,1.494500
28,1780783756,2026-06-06T22:09:16Z,88052514,0x3ac6c0ddc74ebeb438cd2721a893c11648736946513ba229f5b11a5acd9ef41d,563560,2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,0x1327e266fc9be1633a355b6d71206eeb9ce30119,maker,0.050,17.010000,0.850500
29,1780783756,2026-06-06T22:09:16Z,88052514,0x3ac6c0ddc74ebeb438cd2721a893c11648736946513ba229f5b11a5acd9ef41d,563560,2448208,0x1d6722398bd5dd747b923042fc2c67f7d31e3d10b305cfd5cb2aee23884d0684,0x712be8f7388a7ac628e835463c48ffb6a40e100d,taker,0.050,-17.010000,0.850500
30,1780783756,2026-06-06T22:09:16Z,88052514,0xe5d97f15de344ced79dad54427e13d36929991381c030011cbfe2f6657d92f5f,562243,2444063,0x48f888418459478da09d2f2fa2b1d609b6d72498a13bd683ee844039f35f2675,0x521070c99db06e54af5e8e4a91d6858decdfbd53,maker,0.500,4.000000,2.000000
31,1780783756,2026-06-06T22:09:16Z,88052514,0xe5d97f15de344ced79dad54427e13d36929991381c030011cbfe2f6657d92f5f,562243,2444063,0x48f888418459478da09d2f2fa2b1d609b6d72498a13bd683ee844039f35f2675,0x4db1bd6c5436eb1ef295c660c1d88d3c6c52528c,taker,0.500,-4.000000,2.000000
32,1780783756,2026-06-06T22:09:16Z,88052514,0x179ab8a439cc65e0b2519b4a1550750de707ab040b7cd7c4130586ee4f11534e,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-8.000000,7.760000
33,1780783756,2026-06-06T22:09:16Z,88052514,0x179ab8a439cc65e0b2519b4a1550750de707ab040b7cd7c4130586ee4f11534e,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xcdec78fa872e1771bcba800b74cc1aa565d15102,taker,0.030,8.000000,7.760000
34,1780783756,2026-06-06T22:09:16Z,88052514,0xec07377ee6fc6c9b73da2f05ba0180bdc31bdc8e6bd82fe3f7f6d5180f5fa0c8,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-2.020617,1.959998
35,1780783756,2026-06-06T22:09:16Z,88052514,0xec07377ee6fc6c9b73da2f05ba0180bdc31bdc8e6bd82fe3f7f6d5180f5fa0c8,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0x580dbe563496d8c57c8c724f761c9ca4b02ccfb5,taker,0.030,2.020617,1.959998
36,1780783756,2026-06-06T22:09:16Z,88052514,0x230a7d81eb345da2931fc66d4b7c41dba003e29cfd6a0e68142c49bad82d792b,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b,maker,0.030,-101.000000,97.970000
37,1780783756,2026-06-06T22:09:16Z,88052514,0x230a7d81eb345da2931fc66d4b7c41dba003e29cfd6a0e68142c49bad82d792b,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xecfa588c316e9edb58e9730a1b8d8db757577fe0,taker,0.030,101.000000,97.970000
38,1780783756,2026-06-06T22:09:16Z,88052514,0xef1a05c099d5f23e11d0269872540d87f1160ff17ec77959d46556154df3d89b,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0x2855555a48ee7ec2e67272701651bfe77034ebe8,maker,0.040,118.340000,113.606400
39,1780783756,2026-06-06T22:09:16Z,88052514,0xef1a05c099d5f23e11d0269872540d87f1160ff17ec77959d46556154df3d89b,563571,2448221,0xb862d8ac42449912b6a645b041aca52131e6cc8081e18f4906452af90a8bb78b,0xb41c082290933df8904699cf67895d60ffd95bd3,taker,0.040,-118.340000,113.606400

                                           user   role  rows   net_tokens   usd_amount
132  0xd594c3f395c3955b8b06aa5fb428b514bbf29d1b  maker    44 -1051.019457  1019.488863
114  0xb41c082290933df8904699cf67895d60ffd95bd3  taker    13  -625.000000   600.000000
150  0xee55214ee3a9ee22a404663c76ca832577df7b04  maker     5    14.983320     1.498332
12   0x16bc7faccdb6dedd07d47333a6f06fef635dd23a  taker     4    73.790000    71.576300
138  0xdcef920c3c532ae6f0e195c86bafb6fd4894d05c  taker     4   -20.000000     1.000000
117  0xbf17c1643131948cc5aecb890e915b124e7540be  maker     4    11.111977     1.000078
65   0x6a8d1709bfb718d8555d315a983c4816278350f9  taker     4   -16.840000    11.675200
70   0x710cad178b1e6fec99981fd7ff48fc05c7bd78ea  taker     4   299.750000   550.140000
98   0x9a960907c9afdb060e480e0a95eef0406a41cf5c  taker     4   -25.858629    12.918630
143  0xe9076a87c5ed90ef16e6fe6529c943baeca0cff6  taker     3    -3.645813     7.567775
126  0xcaad1b3a62d286214f94ace993a1e80e44aa255c  maker     3   416.660000   399.993600
23   0x2acf345851bd6dbcee9c07d157f58386a4fdf9bb  maker     3    16.786843     4.532448
78   0x7c63520c2ca9b336af0c205b9ccf68217bb393d4  maker     3    30.475000     8.533000
95   0x9919a655c2694462950d9ca5a0307202740a0a5d  taker     3    -4.066417     0.386422
32   0x39dbe612dc01dd85bbd5d4e0e524f74e061f13c8  taker     3    -5.906848     3.706849
85   0x8b6e09d89794b16ef9cb9562bcc87464793907d7  taker     3   -12.000000     5.672000
83   0x893575c7d99542163c6b6e8a0fe5af0b6d217daa  maker     3   528.250000   295.820000
151  0xeebde7a0e019a63e6b476eb425505b7b3e6eba30  taker     3   -26.000000     1.300000
27   0x2ed94d1a460379292d2e3b46f2cf7d94b033f271  maker     3    13.890000     0.694500
94   0x98da26e8fa92fc7973af6f95baf5efc4e2493b56  maker     2     6.000000     0.600000

## Viability readout

This small run is viable if the summary shows nonzero decoded events, nonzero trades, and at least some Gamma token mappings. A few unmatched tokens can happen in a tiny live sample or when Gamma does not return metadata for a token query, but a high unmatched rate would be the next thing to investigate before scaling.

Recommended next scale-up after this passes: increase `LOOKBACK_BLOCKS` gradually, keep `BATCH_SIZE` small, raise `MAX_EVENTS`, and write partitioned session files rather than repeatedly overwriting this sample folder.